PR1 - refactor post deletion
CSUN-COMP587-F18/meddit pull request #1
Opened 2018-09-26 06:17 UTC by arminekhachatryan94

Refactored post deletion to use a service and contract.

2018-09-27 01:10 UTC, kyledewey commented
Review requested from @shanth2600

2018-09-27 23:13 UTC, kyledewey commented
Additional review requested from @alejandrom2

2018-10-01 04:37 UTC, shanth2600 requested changes
I would relegate the access control (permissions) to its own service. Also the domain service (post service) shouldn't be dealing with json or HTTP responses. That's stuff that should happen at the infrastructure level (in the controller). ALSO inject the model into the service as a dependency and don't use the static '::' accessor for creating the sql queries. Slack me if you need clarification.

2018-10-03 19:36 UTC, alejandrom2 requested changes

2018-10-03 19:36 UTC, alejandrom2 commented on forum/app/Services/PostService.php
> +        $post = Post::find($id);
I would recommend you used the findOrFail to help handle exception.

2018-10-03 19:36 UTC, alejandrom2 commented on forum/app/Services/PostService.php
> +            ], 401);
Is 401 error the appropriate one for post not found?

2018-10-04 04:43 UTC, alejandrom2 approved these changes

2018-10-05 01:00 UTC, shanth2600 approved these changes

2018-10-05 05:02 UTC, merged